name: ZombieApocalypse
main: com.ericdebouwer.zombieapocalypse.ZombieApocalypse
author: Ericdebouwer (3ricL)
description: Add a zombie apocalypse to minecraft!
website: https://www.spigotmc.org/resources/82106/
api-version: 1.13
version: ${project.version}
softdepend:
  - SilkSpawners
commands:
   apocalypse:
       aliases: [apo]
       usage: "§6USAGE §r/<command> <start | end | reload | setlimit> §7[worldname] [duration | amount]"
   zombie:
       usage: "§6USAGE §r/<command> <egg | spawner> <zombie_type>"
       
permissions:
   apocalypse.*:
      default: false
      children:
         apocalypse.manage: true
         apocalypse.zombie: true
   apocalypse.manage: 
       default: op
   apocalypse.zombie:
       default: op