name: ZombieApocalypse
main: com.ericdebouwer.zombieapocalypse.ZombieApocalypse
author: ericdebouwer (3ricL)
description: Add a zombie apocalypse to minecraft!
website: rebrand.ly/ZombieApocalypse
api-version: 1.13
version: 1.3
commands:
   apocalypse:
       aliases: [apo]
       usage: "§6USAGE §r/<command> <start | end | reload | setlimit> §7[worldname] [duration | amount]"
   zombie:
       usage: "§6USAGE §r/<command> <zombie_type>"
       
permissions:
   apocalypse.*:
      default: false
      children:
         apocalypse.manage: true
         apocalypse.zombie: true
   apocalypse.manage: 
       default: op
   apocalypse.zombie:
       default: op